#!/usr/bin/env python3
"""
Code Refactoring — Dependency & Change Impact Analyzer

Scans target directories to build dependency maps, identify symbol usages,
and estimate change impact for refactoring planning. Supports Python (.py),
C# (.cs), TypeScript/JavaScript (.ts/.js), and Java (.java).

Auto-generated file exclusion: Automatically filters out .g.cs, Designer.cs,
*.generated.cs files and any C# file containing <auto-generated /> directive.
This prevents false-positive analysis of ephemeral code generator output.

Usage:
    python refactor_analyze.py --target-dir <path> [--symbol NAME] [--language py|cs|ts|java] [--output PATH]

Output:
    - JSON report with dependency map, usage counts, and change-impact estimates
    - Human-readable summary printed to stdout
"""

import argparse
import json
import os
import re
import sys
from collections import defaultdict
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Optional


@dataclass
class SymbolRef:
    """A reference to a symbol found in a file."""
    file_path: str
    line_number: int
    context_line: str  # trimmed surrounding code for context
    ref_type: str  # call, inherit, import, assign, etc.


@dataclass
class SymbolDefinition:
    """A definition of a symbol (function/class/method)."""
    name: str
    file_path: str
    line_number: int
    kind: str  # class, function, method, variable, interface
    visibility: str = "public"  # public, protected, private
    signature: str = ""  # full declaration line or minimal signature
    parameters: list[str] = field(default_factory=list)
    return_type: str = ""


@dataclass
class ChangeImpact:
    """Estimated impact of changing a symbol."""
    symbol_name: str
    defining_file: str
    direct_callers: list[dict] = field(default_factory=list)
    transitive_deps: list[dict] = field(default_factory=list)
    test_files_affected: list[str] = field(default_factory=list)
    breaking_risk: str = "none"  # none, low, medium, high
    estimated_change_count: int = 0  # number of files that need changes


# Language-specific parsers

# Auto-generated file patterns that MUST be excluded from analysis.
# These are ephemeral artifacts produced by code generators, designers, and build tools.
AUTO_GENERATED_PATTERNS = [
    re.compile(r'\.g\.(cs|ts|js)$', re.IGNORECASE),       # *.g.cs, *.g.ts
    re.compile(r'Designer\.(cs|ui)$', re.IGNORECASE),      # *Designer.cs, *Designer.ui
    re.compile(r'(?:generated?|gen)\.', re.IGNORECASE),     # *.generated.cs, *.gen.cs
    re.compile(r'T4Template|TessyGen_'),                   # T4 template output patterns
]

AUTO_GENERATED_DIRECTIVES = [
    '<auto-generated />',
    '<autogenerated>',
    '// <auto-generated/>',
    '// This code was auto-generated.',
    'This code was generated by a tool.',
    'Generated by NSwag',
    'Generated from OpenAPI',
    'DO NOT EDIT THIS FILE',
    '// <copyright file="',                                    # NSwag/SourceGen pattern start
    '#pragma warning disable CS8019',                          # Generated suppressions
]

# Directives indicating the developer-authored portion of a partial/generated class.
DEVELOPER_AUTHORED_DIRECTIVES = [
    '// <summary>',                                            # XML doc in partials
    'partial void ',                                           # Partial method declarations (developer-written)
    'partial record ',                                         # Partial records (developer-written)
]


def is_auto_generated_file(file_path: str, language: str) -> bool:
    """Check if a file matches auto-generated naming patterns."""
    basename = os.path.basename(file_path).lower()
    for pattern in AUTO_GENERATED_PATTERNS:
        if pattern.search(basename):
            return True
    return False


def has_auto_generated_directive(file_path: str) -> bool:
    """Check if the first 20 lines contain an auto-generated directive.
    Used as secondary check for files that don't match naming conventions.
    Returns True only for C# and VB files (where directives are standard).
    """
    try:
        with open(file_path, 'r', encoding='utf-8', errors='replace') as f:
            header = ''.join(f.readline() for _ in range(20))
        for directive in AUTO_GENERATED_DIRECTIVES:
            if directive.lower() in header.lower():
                return True
    except (OSError, IOError):
        pass
    return False


LANGUAGE_PATTERNS = {
    "py": {
        "class_def": re.compile(r'^\s*class\s+(\w+)(?:\(([^)]*)\))?\s*:'),
        "function_def": re.compile(r'^\s*def\s+(\w+)\s*\((.*?)\)\s*(?:->\s*(\S+))?\s*:', re.MULTILINE),
        "import_from": re.compile(r'from\s+(\S+)\s+import\s+(.*)'),
        "import_module": re.compile(r'import\s+(\S+)'),
        "method_call": re.compile(r'\b(\w+)\s*\('),
    },
    "cs": {
        "class_def": re.compile(r'(?:public|private|protected|internal)?\s*class\s+(\w+)(?:\s+:\s+(\w+))?\s*\{', re.MULTILINE),
        "interface_def": re.compile(r'(?:public|private|protected|internal)?\s*interface\s+(\w+)(?:\s+:\s+(\w+))?\s*\{', re.MULTILINE),
        "method_sig": re.compile(
            r'(?:public|private|protected|internal|static|virtual|override|abstract)\s+'
            r'(?:(?P<return>\w+(?:<[^>]+>)?(?:\[\])?)\s+)?(?P<name>\w+)\s*'
            r'\((?P<params>[^)]*)\)',
            re.MULTILINE,
        ),
        "using_directive": re.compile(r'^\s*using\s+(\S+)'),
    },
    "ts": {
        "class_def": re.compile(r'class\s+(\w+)(?:\s+extends\s+(\w+))?\s*\{', re.MULTILINE),
        "interface_def": re.compile(r'interface\s+(\w+)(?:\s+extends\s+(\w+))?\s*\{', re.MULTILINE),
        "function_decl": re.compile(
            r'(?:export\s+)?(?:async\s+)?function\s+(\w+)\s*\((.*?)\)\s*(?::\s*(\S+))?\s*\{?',
            re.MULTILINE,
        ),
    },
}


def scan_symbols(file_path: str, language: str) -> list[SymbolDefinition]:
    """Extract symbol definitions from a source file."""
    symbols = []
    try:
        with open(file_path, 'r', encoding='utf-8', errors='replace') as f:
            lines = f.readlines()
    except (OSError, IOError):
        return symbols

    patterns = LANGUAGE_PATTERNS.get(language, {})
    if not patterns:
        return symbols

    for i, line in enumerate(lines, start=1):
        # Class definitions
        m = patterns.get('class_def', re.compile(r'')).match(line)
        if m:
            name = m.group(1)
            base = m.group(2) or ""
            visibility = "public" if any(w in line.lower() for w in ['public', 'internal']) else "private"
            symbols.append(SymbolDefinition(
                name=name, file_path=file_path, line_number=i, kind="class",
                visibility=visibility, signature=line.strip(), parameters=[],
            ))

        # Interface definitions (C# only)
        if language == 'cs':
            m = patterns.get('interface_def', re.compile(r'')).match(line)
            if m:
                symbols.append(SymbolDefinition(
                    name=m.group(1), file_path=file_path, line_number=i, kind="interface",
                    visibility="public", signature=line.strip(), parameters=[],
                ))

        # Function/method definitions
        m = patterns.get('function_def', re.compile(r'')).match(line) or \
            patterns.get('method_sig', re.compile(r'')).search(line) or \
            patterns.get('function_decl', re.compile(r'')).match(line)
        if m:
            name = m.group(1)
            params_str = (m.group(2) or "").strip()
            return_type = (m.group(3) or "").strip().rstrip(':').rstrip('{')
            kind = "method" if 'def ' in line or 'override' in line else ("class_method" if language == 'cs' and ':' not in line.split('(')[0].split()[-1] else "function")

            # Handle C# method detection more carefully
            if language == 'cs':
                parts_before_paren = line[:line.index('(')] if '(' in line else ''
                last_word = parts_before_paren.strip().split()[-1] if parts_before_paren.strip() else ''
                kind = "method" if last_word.isidentifier() and last_word != name else "function"

            params = [p.strip().split(':')[-1].strip().split('=')[0].strip().split('.')[-1] for p in params_str.split(',') if p.strip()] if params_str else []

            symbols.append(SymbolDefinition(
                name=name, file_path=file_path, line_number=i, kind=kind,
                visibility="public", signature=line.strip(), parameters=params[:5],  # cap params display
                return_type=return_type or "",
            ))

    return symbols


def find_symbol_refs(file_path: str, symbol_name: str, language: str) -> list[SymbolRef]:
    """Find all references to a symbol in a source file."""
    refs = []
    try:
        with open(file_path, 'r', encoding='utf-8', errors='replace') as f:
            lines = f.readlines()
    except (OSError, IOError):
        return refs

    if language == "py":
        patterns = [
            re.compile(r'\b' + re.escape(symbol_name) + r'\b'),  # any usage
        ]
        ref_types_map = {
            'import': re.compile(r'(?:from\s+\S+\s+)?import\s+(?:\w+,)*\s*' + re.escape(symbol_name)),
            'call': re.compile(r'\b' + re.escape(symbol_name) + r'\s*\('),
            'inherit': re.compile(r'class\s+\w+\(([^)]*)' + re.escape(symbol_name) + r')'),
        }
    elif language == "cs":
        patterns = [re.compile(r'\b' + re.escape(symbol_name) + r'\b')]
        ref_types_map = {
            'using': re.compile(r'^\s*using\s+\S+' + re.escape(symbol_name)),
            'call': re.compile(r'\b' + re.escape(symbol_name) + r'\s*\('),
            'inherit': re.compile(r'(?:class|interface)\s+\w+(?:\s+:\s+\w+,)?(?:\s*,?\s*)*' + re.escape(symbol_name) + r'\b'),
        }
    else:
        patterns = [re.compile(r'\b' + re.escape(symbol_name) + r'\b')]
        ref_types_map = {}

    for i, line in enumerate(lines, start=1):
        stripped = line.strip()
        if stripped.startswith('#') or stripped.startswith('//'):
            continue  # skip comments

        for pat in patterns:
            if pat.search(line):
                # Determine reference type
                ref_type = "usage"
                for rt, rpat in ref_types_map.items():
                    if rpat.search(line):
                        ref_type = rt
                        break

                context = stripped[:120] + ("..." if len(stripped) > 120 else "")
                refs.append(SymbolRef(
                    file_path=file_path, line_number=i, context_line=context, ref_type=ref_type,
                ))
                break  # one match per line is enough

    return refs


def scan_test_files(target_dir: str, language: str) -> list[str]:
    """Find all test files in the target directory."""
    patterns_by_lang = {
        "py": ["test_*.py", "*_test.py"],
        "cs": ["*Tests.cs", "*.Test.cs"],
        "ts": ["*.spec.ts", "*.test.ts", "**/__tests__/**"],
        "java": ["**/test/**/*Test.java", "**/src/test/**/*Test.java"],
    }

    test_patterns = patterns_by_lang.get(language, ["*test*", "*Test*"])
    test_files = []

    for pattern in test_patterns:
        try:
            import glob
            matches = glob.glob(os.path.join(target_dir, '**', pattern), recursive=True)
            test_files.extend(matches)
        except Exception:
            pass

    return sorted(set(test_files))


def estimate_breaking_risk(symbol: SymbolDefinition, refs: list[SymbolRef]) -> str:
    """Estimate breaking risk based on symbol visibility and reference count."""
    if len(refs) == 0:
        return "none"

    # Check if symbol is public-facing
    if symbol.visibility in ("public",):
        if len(refs) > 10:
            return "high"
        elif len(refs) > 3:
            return "medium"
        else:
            return "low"
    elif symbol.visibility in ("protected", "internal"):
        return "medium"
    else:
        return "none"


def analyze_target(
    target_dir: str,
    language: Optional[str] = None,
    symbol_filter: Optional[str] = None,
) -> dict:
    """Main analysis entry point. Returns structured impact data."""

    # Determine language from file extensions if not specified
    if language is None:
        ext_counts = defaultdict(int)
        for root, _, files in os.walk(target_dir):
            for f in files:
                ext = f.rsplit('.', 1)[-1].lower() if '.' in f else ''
                if ext in LANGUAGE_PATTERNS:
                    ext_counts[ext] += 1
        language = max(ext_counts, key=ext_counts.get) if ext_counts else "py"

    print(f"[code-refactoring-analyzer] Language detected/assumed: {language}")
    print(f"[code-refactoring-analyzer] Scanning target directory: {target_dir}")

    # Phase 1: Scan all source files for symbol definitions
    print("[code-refactoring-analyzer] Phase 1: Scanning for symbol definitions...")
    all_symbols = {}  # name -> list of SymbolDefinition (may be defined in multiple places)
    supported_extensions = set()
    for lang_code in LANGUAGE_PATTERNS:
        ext_map = {"py": ".py", "cs": ".cs", "ts": [".ts", ".tsx"], "java": [".java"]}
        exts = ext_map.get(lang_code, [])
        if isinstance(exts, str):
            exts = [exts]
        supported_extensions.update(exts)

    source_files = []
    auto_gen_excluded = 0
    directive_excluded = 0
    for root, _, files in os.walk(target_dir):
        # Skip common non-source directories
        skip_dirs = {'node_modules', '__pycache__', '.git', 'bin', 'obj', 'dist'}
        if any(d in root.split(os.sep) for d in skip_dirs):
            continue
        for f in files:
            ext = '.' + f.rsplit('.', 1)[-1].lower() if '.' in f else ''
            if ext not in supported_extensions:
                continue
            full_path = os.path.join(root, f).replace('\\', '/')
            # Exclude auto-generated files by naming convention
            if is_auto_generated_file(full_path, language):
                auto_gen_excluded += 1
                continue
            # Secondary check: scan first 20 lines for <auto-generated /> directive (C#)
            if language == 'cs' and has_auto_generated_directive(full_path):
                directive_excluded += 1
                continue
            source_files.append(full_path)

    print(f"[code-refactoring-analyzer] Found {len(source_files)} source files")

    for file_path in source_files[:2000]:  # cap to prevent excessive scanning
        syms = scan_symbols(file_path, language)
        for sym in syms:
            all_symbols.setdefault(sym.name, []).append(sym)

    print(f"[code-refactoring-analyzer] Found {len(all_symbols)} unique symbols")

    # Phase 2: For each symbol (or filter), find references
    print("[code-refactoring-analyzer] Phase 2: Building dependency map...")
    dependencies = {}

    symbols_to_analyze = set()
    if symbol_filter:
        # Check exact match first, then case-insensitive prefix match
        found = False
        for name in list(all_symbols.keys()):
            if name == symbol_filter or name.startswith(symbol_filter + '.'):
                symbols_to_analyze.add(name)
                found = True
        if not found and symbol_filter in all_symbols:
            symbols_to_analyze.add(symbol_filter)
        elif not symbols_to_analyze:
            print(f"[code-refactoring-analyzer] WARNING: No symbols matching '{symbol_filter}' found")
            print(f"  Available symbols (first 20): {sorted(all_symbols.keys())[:20]}...")
    else:
        # Analyze top symbols by reference count (most likely to be impactful changes)
        for sym_name, defs in all_symbols.items():
            if len(defs[0].file_path.split('/')) <= 4:  # skip deeply nested generated files
                symbols_to_analyze.add(sym_name)

    test_files = scan_test_files(target_dir, language)
    print(f"[code-refactoring-analyzer] Found {len(test_files)} test file(s)")

    analyzed_count = 0
    for sym_name in sorted(symbols_to_analyze):
        refs = find_symbol_refs_for_all(
            source_files[:2000], sym_name, language, symbol_filter=symbol_filter is not None
        )

        if not refs and symbol_filter:
            continue  # only include filtered symbols that exist

        primary_def = all_symbols.get(sym_name, [])[0] if sym_name in all_symbols else None

        impact = ChangeImpact(
            symbol_name=sym_name,
            defining_file=primary_def.file_path if primary_def else "unknown",
            direct_callers=[r.__dict__ for r in refs[:50]],  # cap for JSON size
            test_files_affected=[tf for tf in test_files if any(r.file_path == tf for r in refs)],
            breaking_risk=estimate_breaking_risk(primary_def or SymbolDefinition("", "", 0, ""), refs),
            estimated_change_count=len(set(r.file_path for r in refs)) + (1 if primary_def else 0),
        )

        dependencies[sym_name] = asdict(impact)
        analyzed_count += 1

    print(f"[code-refactoring-analyzer] Analyzed {analyzed_count} symbols")

    return {
        "language": language,
        "target_directory": target_dir,
        "total_source_files_scanned": len(source_files[:2000]),
        "auto_generated_excluded_by_pattern": auto_gen_excluded,
        "auto_generated_excluded_by_directive": directive_excluded,
        "unique_symbols_found": len(all_symbols),
        "symbols_analyzed": list(dependencies.keys()),
        "test_files_found": test_files,
        "dependency_map": dependencies,
        "analysis_timestamp": __import__('datetime').datetime.now().isoformat(),
    }


def find_symbol_refs_for_all(
    source_files: list[str], symbol_name: str, language: str, symbol_filter: bool = False
) -> list[SymbolRef]:
    """Find references to a symbol across all source files."""
    all_refs = []
    for file_path in source_files:
        refs = find_symbol_refs(file_path, symbol_name, language)
        if refs or not symbol_filter:  # include even zero-ref symbols when filtering
            all_refs.extend(refs)
    return all_refs


def main():
    parser = argparse.ArgumentParser(description="Code Refactoring Dependency & Impact Analyzer")
    parser.add_argument(
        "--target-dir", required=True, help="Root directory of the target repository"
    )
    parser.add_argument(
        "--language", choices=["py", "cs", "ts", "java"], default=None,
        help="Language to analyze (auto-detected from file extensions if omitted)",
    )
    parser.add_argument(
        "--symbol", default=None,
        help="Filter analysis to a specific symbol name (exact match or prefix)",
    )
    parser.add_argument(
        "--output", default=None,
        help="Output JSON report path (defaults to stdout)",
    )
    parser.add_argument(
        "--verbose", "-v", action="store_true", help="Print progress details"
    )

    args = parser.parse_args()

    target_dir = os.path.abspath(args.target_dir)
    if not os.path.isdir(target_dir):
        print(f"ERROR: Target directory does not exist: {target_dir}", file=sys.stderr)
        sys.exit(1)

    result = analyze_target(target_dir, language=args.language, symbol_filter=args.symbol)

    # Print summary
    print("\n" + "=" * 70)
    print("CODE REFACTORING — ANALYSIS SUMMARY")
    print("=" * 70)
    print(f"Language         : {result['language']}")
    print(f"Source files     : {result['total_source_files_scanned']}")
    print(f"Symbols found    : {result['unique_symbols_found']}")
    print(f"Symbols analyzed : {len(result['symbols_analyzed'])}")
    print(f"Test files       : {len(result['test_files_found'])}")
    if result.get('auto_generated_excluded_by_pattern', 0) > 0 or result.get('auto_generated_excluded_by_directive', 0) > 0:
        gen_count = result.get('auto_generated_excluded_by_pattern', 0)
        dir_count = result.get('auto_generated_excluded_by_directive', 0)
        print(f"Auto-gen excluded: {gen_count} (pattern) + {dir_count} (directive)")
    print()

    # Show high-risk symbols
    high_risk = [
        (name, info) for name, info in result['dependency_map'].items()
        if info.get('breaking_risk') in ('medium', 'high') and not args.symbol
    ]
    if high_risk:
        print("HIGH-RISK SYMBOLS (potential breaking changes):")
        for name, info in sorted(high_risk, key=lambda x: -x[1]['estimated_change_count']):
            risk_label = "🔴 HIGH" if info['breaking_risk'] == 'high' else "🟡 MEDIUM"
            print(f"  {risk_label}  {name}")
            print(f"           Files affected: {info['estimated_change_count']}")
            print(f"           Test files touched: {len(info.get('test_files_affected', []))}")
    elif args.symbol:
        sym_data = result['dependency_map'].get(args.symbol)
        if sym_data:
            print(f"\nSymbol '{args.symbol}' analysis:")
            print(f"  Breaking risk : {sym_data['breaking_risk']}")
            print(f"  Change count  : {sym_data['estimated_change_count']}")

    # Output JSON
    json_output = json.dumps(result, indent=2, default=str)

    if args.output:
        with open(args.output, 'w', encoding='utf-8') as f:
            f.write(json_output)
        print(f"\n[code-refactoring-analyzer] Report written to: {args.output}")
    else:
        print("\n--- JSON REPORT (stdout) ---\n")
        print(json_output)


if __name__ == "__main__":
    main()
